--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Oct 09 2018 15:40
-- Script Generated by Database Design Studio 2.21.3 
--


--
-- Create Table    : 'City'   
-- CityID          :  
-- CityName        :  
-- PostNumber      :  
-- Country         :  
--
CREATE TABLE City (
    CityID         BIGINT IDENTITY(1,1) NOT NULL,
    CityName       CHAR NOT NULL,
    PostNumber     INT NOT NULL,
    Country        INT NOT NULL,
CONSTRAINT pk_City PRIMARY KEY CLUSTERED (CityID))
GO

--
-- Create Table    : 'Provider'   
-- ProviderID      :  
-- ProviderName    :  
--
CREATE TABLE Provider (
    ProviderID     BIGINT IDENTITY(1,1) NOT NULL,
    ProviderName   CHAR NOT NULL,
CONSTRAINT pk_Provider PRIMARY KEY CLUSTERED (ProviderID))
GO

--
-- Create Table    : 'Address'   
-- AddressID       :  
-- PersonID        :  
-- StreetName      :  
-- HouseNumber     :  
-- CityID          :  
-- AlternativeAddressID :  
-- CityID          :  (references City.CityID)
--
CREATE TABLE Address (
    AddressID      BIGINT IDENTITY(1,1) NOT NULL,
    PersonID       INT NOT NULL,
    StreetName     CHAR NOT NULL,
    HouseNumber    CHAR NOT NULL,
    CityID         INT NOT NULL,
    AlternativeAddressID INT NOT NULL,
    CityID         BIGINT NOT NULL,
CONSTRAINT pk_Address PRIMARY KEY CLUSTERED (AddressID),
CONSTRAINT fk_Address FOREIGN KEY (CityID)
    REFERENCES City (CityID)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'Person'   
-- PersonID        :  
-- FirstName       :  
-- MiddleName      :  
-- LastName        :  
-- Email           :  
-- Notes           :  
-- AddressID       :  
-- TelefonID       :  
-- AAID            :  
-- AddressID       :  (references Address.AddressID)
--
CREATE TABLE Person (
    PersonID       BIGINT IDENTITY(1,1) NOT NULL,
    FirstName      CHAR NOT NULL,
    MiddleName     CHAR NOT NULL,
    LastName       CHAR NOT NULL,
    Email          CHAR NOT NULL,
    Notes          CHAR NOT NULL,
    AddressID      BIGINT NOT NULL,
    TelefonID      INT NOT NULL,
    AAID           INT NOT NULL,
    AddressID      BIGINT NOT NULL,
CONSTRAINT pk_Person PRIMARY KEY CLUSTERED (PersonID),
CONSTRAINT fk_Person FOREIGN KEY (AddressID)
    REFERENCES Address (AddressID)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'Telefon'   
-- TelefonID       :  
-- TelefonNumber   :  
-- ProviderID      :  
-- TelefonType     :  
-- PersonID        :  (references Person.PersonID)
-- ProviderID      :  (references Provider.ProviderID)
--
CREATE TABLE Telefon (
    TelefonID      BIGINT IDENTITY(1,1) NOT NULL,
    TelefonNumber  INT NOT NULL,
    ProviderID     BIGINT NOT NULL,
    TelefonType    CHAR NOT NULL,
    PersonID       BIGINT NOT NULL,
    ProviderID     BIGINT NOT NULL,
CONSTRAINT pk_Telefon PRIMARY KEY CLUSTERED (TelefonID),
CONSTRAINT fk_Telefon FOREIGN KEY (PersonID)
    REFERENCES Person (PersonID)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
CONSTRAINT fk_Telefon2 FOREIGN KEY (ProviderID)
    REFERENCES Provider (ProviderID)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'AlternativeAddress'   
-- PersonID        :  (references Person.PersonID)
-- AddressID       :  (references Address.AddressID)
-- AAType          :  
-- AAID            :  
-- PersonID1       :  
-- Address         :  
--
CREATE TABLE AlternativeAddress (
    PersonID       BIGINT NOT NULL,
    AddressID      BIGINT NOT NULL,
    AAType         CHAR(1) NOT NULL,
    AAID           INT NOT NULL,
    PersonID1      INT NOT NULL,
    Address        INT NOT NULL,
CONSTRAINT pk_AlternativeAddress PRIMARY KEY CLUSTERED (PersonID,AddressID),
CONSTRAINT fk_AlternativeAddress FOREIGN KEY (PersonID)
    REFERENCES Person (PersonID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
CONSTRAINT fk_AlternativeAddress2 FOREIGN KEY (AddressID)
    REFERENCES Address (AddressID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
GO

--
-- Create Table    : 'Notes'   
-- NotesID         :  
-- NotesText       :  
-- PersonID        :  (references Person.PersonID)
--
CREATE TABLE Notes (
    NotesID        BIGINT IDENTITY(1,1) NOT NULL,
    NotesText      NVARCHAR(2000) NOT NULL,
    PersonID       BIGINT NOT NULL,
CONSTRAINT pk_Notes PRIMARY KEY CLUSTERED (NotesID),
CONSTRAINT fk_Notes FOREIGN KEY (PersonID)
    REFERENCES Person (PersonID)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
GO

--
-- Create Table    : 'Email'   
-- EmailID         :  
-- EmailAddress    :  
-- PersonID        :  (references Person.PersonID)
--
CREATE TABLE Email (
    EmailID        BIGINT IDENTITY(1,1) NOT NULL,
    EmailAddress   NVARCHAR(100) NOT NULL,
    PersonID       BIGINT NOT NULL,
CONSTRAINT pk_Email PRIMARY KEY CLUSTERED (EmailID),
CONSTRAINT fk_Email FOREIGN KEY (PersonID)
    REFERENCES Person (PersonID)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
GO
