--
-- Target: Microsoft SQL Server 
-- Syntax: isql /Uuser /Ppassword /Sserver -i\path\filename.sql
-- Date  : Oct 09 2018 15:40
-- Script Generated by Database Design Studio 2.21.3 
--


--
-- Create Table    : 'City'   
-- CityID          :  
-- CityName        :  
-- PostNumber      :  
-- Country         :  
--
CREATE TABLE City (
    CityID         BIGINT IDENTITY(1,1) NOT NULL,
    CityName       NVARCHAR(MAX) NOT NULL,
    PostNumber     NVARCHAR(MAX) NOT NULL,
    Country        NVARCHAR(MAX) NOT NULL,
CONSTRAINT pk_City PRIMARY KEY CLUSTERED (CityID))